version: '3.7'

networks:
  db_mysql_network:
    name: db_mysql_network
    external: false

services:
  mysql:
    container_name: mysql_core
    volumes:
      - /srv/container/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=Ojolali123
    command:
      --character-set-server=utf8
    ports:
      - 33061:3306
    image: "docker.io/mysql:latest"
    restart: always
    networks:
      - db_mysql_network

